### ISSUE TITLE
[Spike] Decouple tdl-auth from it dependencies 

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/tdl-auth#9]
Send an SQS event when a candidate downloads the credentials but to achieve this, we need to first untangle a project: https://github.com/julianghionoiu/tdl-auth

It needs to be refactored so that it can be tested locally for this, a local KMS might need to be implemented

Goals:
- create local KMS
- decouple tdl-auth from it dependencies
- run project locally
- send SQS event when a candidate downloads credentials before embarking on the path to the BeFaster challenge 

Local stubs needed:
- S3
- SQS
- KMS
- IAM (local-federated-iam: GetFederationTokenRequest)

**Comment by neomatrix369** [comment]
Readme mentions this command:

```bash
java -Dlogback.configurationFile=`pwd`/logback.xml  \
    -jar ./build/libs/tdl-auth-0.0.1-all.jar \
    --region eu-west-2 \
    --bucket tdl-test \
    --scope test \
    --username fed01 \
    --challenge HLX \
    --file ./build/aws-test-secrets
```
and also

```bash
cat ./build/aws-test-secrets | pbcopy
```
Could not locate `./build/aws-test-secrets` in the project

**Comment by julianghionoiu** [comment]
That is because it contains real AWS credentials.

**Comment by julianghionoiu** [comment]
Hence why we need to sort out the local testing first

**Comment by neomatrix369** [comment]
I#ll take a look again, starting from the individual tests first
